[package]
name = "deuterium"
version = "0.1.0"
edition = "2021"

[lib]
name = "deuterium"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies.pyo3]
version = "0.18.3"
features = ["extension-module"]

[dependencies]
nalgebra = "0.32.1"
approx = "0.5.1"
